### ISSUE TITLE
No module named 'wavecraft'

### ISSUE THREAD

**Issue by jackisshortforjohn** [tefdara/Wave-Craft#3]
Hey dude, I can't run wac.py, I just get the following:

```
Traceback (most recent call last):
  File "/Users/jack/git/Wave-Craft/wavecraft/./wac.py", line 6, in <module>
    from wavecraft import *
ModuleNotFoundError: No module named 'wavecraft'

```
Something to do with the path stuff you did in your last commit maybe?

Cheers man, hope the work's going alright :)

**Comment by tefdara** [comment]
Hey Jack, yeah sorry about that. I was experimenting and was getting around this by appending the wavecraft path to `sys.path` and that is no good. I've updated the  namespaces and moved wac.py to the outer directory. It should work now but let me know if  you had any other issues.

**Comment by tefdara** [comment]
Let me know if you had any other issues related to this.
